server:
  port: 8081
spring:
  application:
    name: 'fornecedor'
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/fornecedor
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
