server:
  port: 8089
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/fornecedor
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
